# Generated by Django 3.2 on 2023-08-16 04:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20230816_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 16, 4, 22, 40, 334306, tzinfo=utc)),
        ),
    ]
